#!/bin/bash

set -e

# Go
if [ "$1" = "go" ]; then
    # Install native dependencies
    apt update
    apt install -y curl

    # Configure Git
    git config --global --add safe.directory '*'

    # Install bagop
    curl -L -o /tmp/bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
    install /tmp/bagop /usr/local/bin

    # Build
    CGO_ENABLED=0 bagop -j "$(nproc)" -b bagccgop -x '(android/*|ios/*|plan9/*|aix/*|linux/loong64|freebsd/riscv64|openbsd/mips64)' main.go

    exit 0
fi

# gccgo
if [ "$1" = "gccgo" ]; then
    # Install native dependencies
    apt update
    apt install -y golang git

    # Configure Git
    git config --global --add safe.directory '*'

    # Build
    GOFLAGS='-gccgoflags=-static' go run main.go -j "$(nproc)" -b bagccgop -x '(linux/alpha|linux/mipsle|linux/arm$|linux/arm64|linux/386|linux/amd64|linux/s390x|linux/ppc64|linux/riscv64|linux/mips64|linux/ppc64le)' main.go

    exit 0
fi
