#!/bin/bash

set -e

# Go
if [ "$1" = "go" ]; then
    # Install native dependencies
    apt update
    apt install -y curl

    # Install bagop
    curl -L -o /tmp/bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
    install /tmp/bagop /usr/local/bin

    # Build
    CGO_ENABLED=0 bagop -j "$(nproc)" -b bagccgop -x '(android/*|ios/*|openbsd/mips64)' main.go

    exit 0
fi

# gccgo
if [ "$1" = "gccgo" ]; then
    # Build
    GOFLAGS='-gccgoflags=-static' go run main.go -j "$(nproc)" -b bagccgop -x '(linux/alpha|linux/mipsle|linux/386|linux/amd64|linux/arm|linux/arm64|linux/mips|linux/mips64|linux/mips64le|linux/mipsle|linux/ppc64|linux/ppc64le|linux/riscv64|linux/s390x)' main.go

    exit 0
fi
